### ISSUE TITLE
Add a GPL license, as required

### ISSUE THREAD

**Issue by masak** [bergsans/pixly-typography#1]
Hello. As the original creator of this font, I strongly advise that you @bergsans add a license to this repository. The original repository (which is still private as of 2021-07-08) is [licensed with GPL-3](https://github.com/masak/cga-typography/blob/master/LICENSE). According to this license, any derivative works also need to be licensed with GPL-3.

Thank you.

**Comment by bergsans** [comment]
Done! I would've linked to your Bel-repo, @masak, but it's currently set to private.  Remind me in the future (if you want to) in a mail or here, and I will add a link to your Bel solution. Best, Claes-Magnus
